better ci and renovate

diff --git a/.github/workflows/_frontend_ci.yaml b/.github/workflows/_frontend_ci.yaml
--- a/.github/workflows/_frontend_ci.yaml
+++ b/.github/workflows/_frontend_ci.yaml
@@ -30,7 +30,7 @@ jobs:
           has_changes=${{ contains(env.CHANGED_FILES, 'frontend/') }}
           echo HAS_CHANGES=${has_changes} >> ${GITHUB_OUTPUT}
 
-  build:
+  ci:
     runs-on: ubuntu-latest
     if: needs.check_frontend_changed_files.outputs.has_changed == 'true'
 
@@ -57,3 +57,17 @@ jobs:
 
       - name: Audit checker
         run: npm audit --audit-level medium --omit=dev
+
+  end:
+    runs-on: ubuntu-latest
+    needs: ci
+    steps:
+      - name: Notify
+        run: |
+          if [ ${{ needs.ci.result }} == 'success' ]; then
+            echo "All tests passed"
+            exit 0
+          else
+            echo "Tests failed"
+            exit 1
+          fi
