better ci and renovate (#145)
* better ci and renovate

* add status end

* add merge group

diff --git a/.github/workflows/_proxy_ci.yaml b/.github/workflows/_proxy_ci.yaml
--- a/.github/workflows/_proxy_ci.yaml
+++ b/.github/workflows/_proxy_ci.yaml
@@ -1,6 +1,7 @@
 name: ci proxy
 
 on:
+  merge_group:
   pull_request:
     paths:
       - 'proxy/**'
@@ -68,3 +69,17 @@ jobs:
       - name: Test
         run: |
           make tests
+
+  end:
+    runs-on: ubuntu-latest
+    needs: ci
+    steps:
+      - name: Notify
+        run: |
+          if [ ${{ needs.ci.result }} == 'success' ]; then
+            echo "All tests passed"
+            exit 0
+          else
+            echo "Tests failed"
+            exit 1
+          fi
